Feature/edit screen login
Tiago-C-Brandao/na-hora-certa pull request #2
Opened 2022-09-14 22:13 UTC by Tiago-C-Brandao

2022-09-14 22:34 UTC, ramirezmz requested changes

2022-09-14 22:34 UTC, ramirezmz commented on pages/login.vue
> +        <input type="text">
You can put class on input

2022-09-14 22:34 UTC, ramirezmz commented on pages/login.vue
> +        <input type="text">
You can put class on input

2022-09-14 22:34 UTC, ramirezmz commented on pages/login.vue
> +        <button>LOGIN</button>
You can put class here

2022-09-14 22:34 UTC, ramirezmz commented on pages/login.vue
> +    * {
Is this indentation correct?

2022-09-15 17:21 UTC, Tiago-C-Brandao commented on pages/login.vue
> +        <input type="text">
Create class on input

2022-09-15 17:22 UTC, merged